Add Multi-Chain IBC Transfers Example
subquery/cosmos-subql-starter pull request #54
Opened 2023-11-20 19:42 UTC by bgodlin

2023-11-20 21:30 UTC, deverka approved these changes
Looks good to me, but we also need @jamesbayly to have a look

2023-11-22 21:01 UTC, deverka commented
@jamesbayly are you able to check this one?

2023-11-27 04:40 UTC, jamesbayly requested changes

2023-11-27 04:40 UTC, jamesbayly commented on Multi-Chain/osmosis-cosmos-bridge/README.md
> +**The SubQuery project is responsible for indexing all IBC transfer events occurring between Cosmos Hub and Osmosis**
```suggestion
**This SubQuery project indexes all IBC transfer events between Cosmos Hub and Osmosis**
```

2023-11-27 04:40 UTC, jamesbayly commented on Multi-Chain/osmosis-cosmos-bridge/docker-compose.yml
> +      - --batch-size=1
```suggestion
```
Don't commit this kind of batch-size

2023-11-27 04:40 UTC, jamesbayly commented on Multi-Chain/osmosis-cosmos-bridge/package.json
> +  "description": "This project can be use as a starting point for developing your Cosmos (Cosmos Hub) based SubQuery project",
Update to match the readme
```suggestion
  "description": "This SubQuery project indexes all IBC transfer events between Cosmos Hub and Osmosis",
```

2023-11-27 04:40 UTC, jamesbayly commented on Multi-Chain/osmosis-cosmos-bridge/schema.graphql
> +type CosmosToOsmosisBridge @entity {
Can you Rename this simple to `BridgeEvent`
`CosmosToOsmosisBridge` kinda infers that this is one-directional between Cosmos -> Osmosis
Then in the future it's easy for us to add other networks to this project

2023-11-27 04:40 UTC, jamesbayly commented on Multi-Chain/osmosis-cosmos-bridge/src/mappings/mappingHandlers.ts
> +  logger.warn(
Instead of `logger.warn`, these should instead all be `logger.info`

2023-11-27 12:50 UTC, merged